### ISSUE TITLE
Bug: Doesn't work with an ad blocker

### ISSUE THREAD

**Issue by waldoj** [presidential-innovation-fellows/vote-2016#99] opened 2016-02-09 01:55 UTC
Observed behavior: Selecting a state does nothing.

Expected behavior: Selecting a state would display some state-specific information.

Steps to reproduce:
1. Install an ad blocker.
2. Make sure that it's blocking Google Analytics (as not all do).
3. Load [the site](https://vote.usa.gov/).
4. Select a state from the menu.

For anybody running an ad blocker, the site does not work at all. It appears that you're triggering the display of state-specific data not based on a `.change()` event—instead, I assume you're using that event to fire off a Google Analytics event, and chaining _that_ to a DIV update. The use of an ad blocker causes the GA event to fail, preventing the DIV update from ever happening.

**Comment by anselmbradford** [comment] 2016-02-28 20:31
Yeah just ran into this because the drop-down did nothing when the state is selected. I think it may not be the event chaining but rather there's a call to `ga(…)` when `ga` is undefined, so it throws an error and stops running further JS. I haven't dug into it deep though.

**Comment by ascott1** [comment] 2016-03-02 19:30
I can confirm that this also occurs when using [Ghostery](https://www.ghostery.com/) with analytics tracking disabled.

**Comment by msecret** [comment] 2016-03-22 21:24
I can confirm this with [Privacy Badger](https://www.eff.org/privacybadger) as well.

I don't think `ga` events should break a page, maybe existence of `ga` could be checked before calling it to avoid an error that stops the rest of the script?

**Comment by jlev** [comment] 2016-03-23 18:50
Looks like this was fixed with ac69bbc. Thanks @adamsfallen!

**Comment by anselmbradford** [comment] 2016-03-25 17:49
Sorry to be a downer, but I'm pretty sure GTM should go at the beginning of the `<body>`, not the bottom: https://support.google.com/tagmanager/answer/6103696#AddingTheContainerSnippet

> Paste this snippet into your website template page so that it appears immediately after the opening body tag.

If that issue with GTM is fixed, https://github.com/presidential-innovation-fellows/vote-2016/commit/ac69bbc3cc4fea37dab3c67c9a4807035b188d5e will break again. Is there an issue with [checking ga before initializing further code](https://github.com/usagov/vote-2016/pull/1)?

**Comment by rogeruiz** [comment] 2016-03-29 12:04
This has been fixed in #103

**Closed as completed by rogeruiz** 2016-03-29 12:04 UTC
