### ISSUE TITLE
add a link to the github page so people know where to file bugs

### ISSUE THREAD

**Issue by leahbannon** [presidential-innovation-fellows/vote-2016#98] opened 2016-02-09 01:33 UTC

**Comment by rogeruiz** [comment] 2016-03-28 15:30
This is a possible duplicate of #94. Or at the very least, I can tackle both #98 and #94 in a single PR.

**Comment by stroupaloop** [comment] 2016-03-29 14:33
resolved w/ 6ffd7f6

**Closed as completed by stroupaloop** 2016-03-29 14:33 UTC
